mskcc/smile-message-publisher

.circleci/config.yml, .gitignore, pom.xml, src/main/resources/checkstyle.xml, test/scripts/generate_checkstyle_report.sh
- Added config files for circleci integration and mvn checkstyle plugin
=> Integrate CircleCI and checkstyle mvn plugin

src/main/java/org/mskcc/cmo/CmoNewRequestPublisher.java
=> Update IGO request publisher

src/main/java/org/mskcc/cmo/CmoNewRequestPublisher.java
=> Request sample manifest  by sample id instead of list of ids

src/main/java/org/mskcc/cmo/CmoNewRequestPublisher.java
=> Handle 500 internal server errors and report summary

pom.xml, src/main/java/org/mskcc/cmo/publisher/pipeline/limsrest/LimsRequestUtil.java, src/main/java/org/mskcc/cmo/publisher/pipeline/limsrest/LimsRequestWriter.java
=> Switch to jackson databinding, remove gson

src/main/java/org/mskcc/cmo/publisher/CmoMetaDbPublisherPipeline.java
=> Quick fix to options parser

pom.xml, src/main/java/org/mskcc/cmo/publisher/pipeline/config/BatchConfiguration.java, src/main/resources/application.properties.EXAMPLE, src/main/resources/log4j.properties.EXAMPLE
=> Update spring boot version and logging

pom.xml, src/main/resources/application.properties.EXAMPLE
Signed-off-by: Divya Madala <71040191+divyamadala30@users.noreply.github.com>
=> Publisher now works with jetStream

Dockerfile, README.md, src/main/resources/log4j.properties.EXAMPLE
=> Init commit dockerfile setup, update log4j logging and README

src/main/java/org/mskcc/cmo/publisher/pipeline/limsrest/LimsRequestUtil.java
=> Cast delivery date to long

src/main/java/org/mskcc/cmo/publisher/pipeline/limsrest/LimsRequestProcessor.java, src/main/java/org/mskcc/cmo/publisher/pipeline/limsrest/LimsRequestUtil.java
Signed-off-by: Divya Madala <71040191+divyamadala30@users.noreply.github.com>
=> Handles Null pointer errors

.gitignore, src/main/java/org/mskcc/cmo/publisher/pipeline/limsrest/LimsRequestProcessor.java, src/main/java/org/mskcc/cmo/publisher/pipeline/limsrest/LimsRequestUtil.java
=> Update error catching and logging for LimsRest fetching

src/main/java/org/mskcc/cmo/publisher/pipeline/limsrest/LimsRequestUtil.java
=> Keep unique request ids only

pom.xml
=> Update commit hash for messaging library

pom.xml, src/main/java/org/mskcc/cmo/publisher/pipeline/limsrest/LimsRequestWriter.java
=> Update messaging lib

src/main/java/org/mskcc/cmo/publisher/pipeline/limsrest/LimsRequestUtil.java
=> Update requests summary report

pom.xml
=> Update MetaDB dependency versions to latest releases

pom.xml
=> Add test directory to checkstyle checks

pom.xml, src/main/java/org/mskcc/cmo/publisher/pipeline/limsrest/LimsRequestProcessor.java, src/main/java/org/mskcc/cmo/publisher/pipeline/limsrest/LimsRequestWriter.java
=> Update pom and resolve field name issues

src/main/java/org/mskcc/cmo/publisher/pipeline/limsrest/LimsRequestProcessor.java
=> Catch and log errors for sample ids

pom.xml, src/main/java/org/mskcc/cmo/publisher/pipeline/limsrest/LimsRequestWriter.java
=> update metadb dependencies

pom.xml
=> Update messaging lib version

src/main/java/org/mskcc/cmo/publisher/pipeline/metadb/MetadbServiceWriter.java
=> Add requestID to NATS msg ID header

pom.xml
- new commons release: 1.2.1.RELEASE
- new messaging java release: 1.2.1.RELEASE
=> Update commons and messaging-java versions

pom.xml, src/main/java/org/mskcc/smile/publisher/pipeline/limsrest/LimsRequestProcessor.java, src/main/java/org/mskcc/smile/publisher/pipeline/limsrest/LimsRequestUtil.java, src/main/java/org/mskcc/smile/publisher/pipeline/smile_server/SmileServiceReader.java
Add igoComplete to sample manifest
=> Add cmo filter for SMILE service
